# Alacritty config
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 10, y = 10 } opacity = 0.95

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" } bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" } size = 12.0

[cursor]
style = { shape = "Block", blinking = "Off" }

[scrolling]
history = 10000
